=== jm673yahoo/mulesoft-class-subject/src/main/api/subject-post-schema.json
{
  "$schema": "http://json-schema.org/draft-01/schema#",
  "title": "Subject",
  "description": "A subject in school",
  "type": "object",
  "properties": {
    "TITLE": {
    	"description": "The tile of the subject",
      	"type": "string"
    },
    "MAX_NUM": {
    	"description": "The maximum people can be registered for the subject",
      	"type": "integer"
    },
    "AVAILABLE_FLAG": {
      	"description": "The flag of the subject is available",
      	"type": "boolean"
    },
    "id": {
    	"description": "The id for the subject",
      	"type": "integer"
    }
  },
  "required": [
    "TITLE",
    "MAX_NUM",
    "AVAILABLE_FLAG"
  ]
}

=== jm673yahoo/mulesoft-class-subject/src/main/api/examples/subject.json
[
    {
        "TITLE": "MATHTHEMATICS",
        "MAX_NUM": 30,
        "AVAILABLE_FLAG": true,
        "id": 1
    },
    {
        "TITLE": "ENGLISH",
        "MAX_NUM": 50,
        "AVAILABLE_FLAG": true,
        "id": 2
    },
    {
        "TITLE": "FRENCH",
        "MAX_NUM": 50,
        "AVAILABLE_FLAG": false,
        "id": 3
    }
]
